/* 
包含n个action type名称常量的模块
*/

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const REMOVE_USER_TOKEN = 'REMOVE_USER_TOKEN'

export const SET_HEADER_TITLE = 'SET_HEADER_TITLE'

export const RECEIVE_CATEGORYS = 'RECEIVE_CATEGORYS'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'